## configuration file for "replace_txts_with_mapping_csv.py" ##
# NOTE: All fields are required.

INPUT:

  # An input TXT files.
  ORIGINAL_TXTS:
    FOLDER_PATH: './data/original_txts'
    ENCODING: 'utf-8'

  # An input CSV file with columns of find & replace strings.
  REPLACE_MAPPING_CSV:
    PATH: './data/replace_mapping.csv'
    ENCODING: 'utf-8'
    FIND_STRING_COLUMN: 'find'
    REPLACE_STRING_COLUMN: 'replace'

OUTPUT:

  # An existing blank folder path to output replaced TXT files.
  FOLDER_PATH: './results'
